rawdata = {u'Reservations': [{u'Groups': [],
                 u'Instances': [{u'AmiLaunchIndex': 0,
                               u'Architecture': 'x86_64',
                               u'BlockDeviceMappings': [{u'DeviceName': '/dev/sda1',
                                                       u'Ebs': {u'AttachTime': '2016-05-01-16-27-19',
                                                               u'DeleteOnTermination': True,
                                                               u'Status': 'attached',
                                                               u'VolumeId': 'vol-0ed3c42472dde29fc'}}],
                               u'ClientToken': 'DPSAr5354928108794',
                               u'EbsOptimized': False,
                               u'Hypervisor': 'xen',
                               u'IamInstanceProfile': {u'Arn': 'arn:aws:iam::262637777988:instance-profile/Primary',
                                                      u'Id': 'QRWMKZECMHCOHGGDIYZOB'},
                               u'ImageId': 'ami-3d3a6b78',
                               u'InstanceId': 'i-04a10a9a89f05523d',
                               u'InstanceType': 't1.micro',
                               u'KernelId': 'aki-ad3667e8',
                               u'KeyName': 'james',
                               u'LaunchTime': '2016-05-01-19-19-45',
                               u'Monitoring': {u'State': 'disabled'},
                               u'NetworkInterfaces': [{u'Attachment': {u'AttachTime': '2016-05-01-16-27-18',
                                                                    u'AttachmentId': 'eni-attach-fcca7e92',
                                                                    u'DeleteOnTermination': True,
                                                                    u'DeviceIndex': 0,
                                                                    u'Status': 'attached'},
                                                     u'Description': '',
                                                     u'Groups': [{u'GroupId': 'sg-0e6ea9b9',
                                                                u'GroupName': 'launch-wizard-29'}],
                                                     u'Ipv6Addresses': [],
                                                     u'MacAddress': '06:06:b4:06:c4:2f',
                                                     u'NetworkInterfaceId': 'eni-dae414c7',
                                                     u'OwnerId': '262637777988',
                                                     u'PrivateDnsName': 'ip-172-31-64-201.us-west-1.compute.internal',
                                                     u'PrivateIpAddress': '172.31.64.201',
                                                     u'PrivateIpAddresses': [{u'Primary': True,
                                                                            u'PrivateDnsName': 'ip-172-31-64-201.us-west-1.compute.internal',
                                                                            u'PrivateIpAddress': '172.31.64.201'}],
                                                     u'SourceDestCheck': True,
                                                     u'Status': 'in-use',
                                                     u'SubnetId': 'subnet-8569addc',
                                                     u'VpcId': 'vpc-cca3dd3c'}],
                               u'Placement': {u'AvailabilityZone': 'us-west-1a',
                                             u'GroupName': '',
                                             u'Tenancy': 'default'},
                               u'PrivateDnsName': 'ip-172-31-64-201.us-west-1.compute.internal',
                               u'PrivateIpAddress': '172.31.64.201',
                               u'ProductCodes': [],
                               u'PublicDnsName': '',
                               u'RamdiskId': 'ari-00a1c7fc',
                               u'RootDeviceName': '/dev/sda1',
                               u'RootDeviceType': 'ebs',
                               u'SecurityGroups': [{u'GroupId': 'sg-0e6ea9b9',
                                                  u'GroupName': 'launch-wizard-29'}],
                               u'SourceDestCheck': True,
                               u'State': {u'Code': 80,
                                         u'Name': 'stopped'},
                               u'StateReason': {u'Code': 'Client.UserInitiatedShutdown',
                                               u'Message': 'Client.UserInitiatedShutdown: User initiated shutdown'},
                               u'StateTransitionReason': 'User initiated (2016-02-11 19:28:09 GMT)',
                               u'SubnetId': 'subnet-8569addc',
                               u'Tags': [{u'Key': 'Name',
                                        u'Value': 'Fedora'},
                                        {u'Key': 'Role',
                                        u'Value': 'Regression'},
                                        {u'Key': 'Department',
                                        u'Value': 'IT'},
                                        {u'Key': 'Team',
                                        u'Value': 'Dev10a'},
                                        {u'Key': 'Project',
                                        u'Value': 'SysAdmin'}],
                               u'VirtualizationType': 'paravirtual',
                               u'VpcId': 'vpc-cca3dd3c'}],
                 u'OwnerId': '262637777988',
                 u'ReservationId': 'r-0fbb688d2f399e2fa'}],
'ResponseMetadata': {'HTTPHeaders': {'content-type': 'text/xml;charset=UTF-8',
                                   'date': 'Mon, 01 May 2016 01:12:21 GMT',
                                   'server': 'AmazonEC2',
                                   'transfer-encoding': 'chunked',
                                   'vary': 'Accept-Encoding'},
                    'HTTPStatusCode': 200,
                    'RequestId': '171a0078-bcbd-1924-91d8-b5a26cbcb23c',
                    'RetryAttempts': 0}}
