#!/usr/bin/env python

from __future__ import print_function
from builtins import range
from builtins import object
import boto3
import sys
import subprocess
import re
from argparse import ArgumentParser

################################################################################
# scriptname = "ec2"
# scriptbuildnum = "0.2.1"
# scriptbuilddate = "2017-04-17"

################################################################################
#  Classes

class _Getch(object):
    def __init__(self):
        try:
            self.impl = _GetchWindows()
        except ImportError:
            self.impl = _GetchUnix()

    def __call__(self): return self.impl()

class _GetchUnix(object):
    def __init__(self):
        import tty, sys

    def __call__(self):
        import sys, tty, termios
        fd = sys.stdin.fileno()
        old_settings = termios.tcgetattr(fd)
        try:
            tty.setraw(sys.stdin.fileno())
            ch = sys.stdin.read(1)
        finally:
            termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
        return ch

class _GetchWindows(object):
    def __init__(self):
        import msvcrt

    def __call__(self):
        import msvcrt
        return msvcrt.getch()


################################################################################
#  Functions

def setupColor():
    global CLRnormal
    global CLRheading
    global CLRheading2
    global CLRtitle
    global CLRtitle2
    global CLRsuccess
    global CLRwarning
    global CLRerror
    if sys.stdout.isatty():
        ncolors = runBash("tput colors")
        if ncolors != "" and ncolors >= 8:
            # Set Colors
            bold = runBash("tput bold")
            red = runBash("tput setaf 1")
            green = runBash("tput setaf 2")
            yellow = runBash("tput setaf 3")
            blue = runBash("tput setaf 4")
            magenta = runBash("tput setaf 5")
            cyan = runBash("tput setaf 6")
            white = runBash("tput setaf 7")
            # Set Color Theme
            CLRnormal = bold + white
            CLRheading = bold + green
            CLRheading2 = bold + blue
            CLRtitle = bold + cyan
            CLRtitle2 = bold + yellow
            CLRsuccess = bold + green
            CLRwarning = bold + yellow
            CLRerror = bold + red

def colorInstanceStatus(state):
    if state == "running":
        CLRstatus = CLRsuccess
    elif state == "stopped":
        CLRstatus = CLRerror
    elif state == "stopping":
        CLRstatus = CLRwarning
    elif state == "pending":
        CLRstatus = CLRwarning
    elif state == "starting":
        CLRstatus = CLRwarning
    elif state == "start":
        CLRstatus = CLRsuccess
    elif state == "stop":
        CLRstatus = CLRerror
    else:
        CLRstatus = CLRnormal
    return CLRstatus

# def displayVer():
#     print "%s%s%s  ver  %s%s%s - %s%s%s" % (CLRheading, scriptname, CLRnormal, CLRtitle, scriptbuildnum, CLRnormal, CLRtitle, scriptbuilddate, CLRnormal)

def runBash(cmd):
    p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    (output, err) = p.communicate()
    if err:
        p_status = p.wait()
        print("Command exit status / return code : ", p_status)
    return (output.rstrip())

def printWithoutCR(value):
    sys.stdout.write(value)

def printList(listname, displayname):
    print("%sListing %s %s" % (CLRheading, displayname, CLRnormal))
    for x,y in list(listname.items()):
        print("\ti = %s%s%s, %s = %s%s%s" % (CLRtitle, x, CLRnormal, displayname, CLRtitle, y, CLRnormal))

def getArguments():
    nopem = False
    loginuser = ""
    filterType = ""
    filters = ""
    OutputText = ""
    parser = ArgumentParser(description='list info for EC2 instances',
                prog='ec2', version='ec2 0.2.1', usage= 'ec2 [option]')
    parser.add_argument('command', choices=['list', 'start', 'stop', 'ssh'])
    parser.add_argument('inname', nargs='?')
    # parser.add_argument('inname', nargs='?', const='', default='')
    parser.add_argument('--name', '-n', action="store",
                help='instances with specified name')
    parser.add_argument('--id', '-i', action="store",
                help='instances with instance-id')
    parser.add_argument('--running', '-r', action = "store_true",
                help = 'all running instances')
    parser.add_argument('--stopped', '-s', action = "store_true",
                help='all stopped instances')
    parser.add_argument('--nopem', '-p', action = "store_true",
                help='connect without PEM key')
    parser.add_argument('--user', '-u', action="store",
                help='specify ssh username')
    parser.add_argument('--debug', '-d', action="store_true",
                help='debug mode')
    options = parser.parse_args()
    if options.command == "list":
        actionType="list"
        filterType2 = ""
        if options.running:
            filterType = "running"
            filters = "running"
            OutputText = "Running EC2 Instances"
        elif options.stopped:
            filterType = "stopped"
            filters = "stopped"
            OutputText = "Stopped EC2 Instances"
        else:
            filterType = "all"
            OutputText = "All Instances"
    elif options.command == "start":
        actionType = "start"
        filterType2 = "stopped"
    elif options.command == "stop":
        actionType = "stop"
        filterType2 = "running"
    elif options.command == "ssh":
        actionType = "ssh"
        filterType2 = "running"
        if options.nopem:
            nopem = True
        if options.user:
            loginuser = options.user
    if options.inname:
        filterType = "name"
        filters = options.inname
        OutputText = "Instances '{}'".format(options.inname)
    elif options.name:
        filterType = "name"
        filters = options.name
        OutputText = "Instances '{}'".format(options.name)
    elif options.id:
        filterType = "id"
        filters = options.id
        OutputText = "Instance '{}'".format(options.id)
    if options.debug:
        debug = True
    else:
        debug = False
    return (actionType, filterType, filterType2, filters, OutputText, debug, nopem, loginuser)

def getInstanceIDs(filtype, filter):
    instanceID = {}
    if filtype == "id":
        instanceSummaryData = ec2C.describe_instances( InstanceIds=["{0}".format(filter)])
    elif filtype == "running" or filtype == "stopped":
        instanceSummaryData = ec2C.describe_instances( Filters =[{'Name':'instance-state-name', 'Values':["{0}".format(filter)]}])
    elif filtype == "name":
        instanceSummaryData = ec2C.describe_instances( Filters =[{'Name':'tag:Name', 'Values':["{0}".format(filter)]}])
    else:
        instanceSummaryData = ec2C.describe_instances()
    for i,v in enumerate(instanceSummaryData['Reservations']):
        ID = v['Instances'][0]['InstanceId']
        instanceID[i] = ID
    numInstances=len(instanceID)
    return (instanceID, numInstances)

def getAMIname(ID):
    instanceImage = ec2R.Image(ID).name
    return (instanceImage)

def getInstanceDetails(qty,idlist):
    instanceState = {}
    instanceAMI = {}
    instanceName = {}
    instanceAMIName = {}
    for i in range(qty):
        instanceData = ec2R.Instance(idlist[i])
        instanceState[i] = instanceData.state['Name']
        instanceAMI[i] = instanceData.image_id
        instanceTag = instanceData.tags
        for j in range(len(instanceTag)):
            if instanceTag[j]['Key'] == 'Name':
                instanceName[i]=instanceTag[j]['Value']
                break
        instanceAMIName[i] = getAMIname(instanceAMI[i])
    return (instanceState, instanceAMI, instanceName, instanceAMIName)

def refineInstanceList(numInstances, filterType2):
    newQty = numInstances
    for i in range(numInstances):
        if instanceState[i] != filterType2:
            del instanceName[i]
            del instanceID[i]
            del instanceState[i]
            del instanceAMI[i]
            del instanceAMIName[i]
            newQty -= 1
    return (newQty)

def getInstanceConnectInfo(specificid):
    instanceData = ec2R.Instance(specificid)
    # PublicDNS=instanceData.public_dns_name
    instanceIP = instanceData.public_ip_address
    instanceKey = instanceData.key_name
    return (instanceIP, instanceKey)

def displayInstanceList(title, numbered="no"):
    if numbered == "no":
        print("\n%s%s%s\n" % (CLRheading, title, CLRnormal))
    for i in range(numInstances):
        if numbered == "yes":
            print("Instance %s#%s%s" % (CLRwarning, i+1, CLRnormal))
        CLRstatus = colorInstanceStatus(instanceState[i])
        print("\tName: %s%s%s\t\tID: %s%s%s\t\tStatus: %s%s%s" % (CLRtitle, instanceName[i], CLRnormal, CLRtitle, instanceID[i], CLRnormal, CLRstatus, instanceState[i], CLRnormal))
        print("\tAMI: %s%s%s\tAMI Name: %s%s%s\n" % (CLRtitle, instanceAMI[i], CLRnormal, CLRtitle, instanceAMIName[i], CLRnormal))

def selectFromList(OutputText, actionType):
    getch = _Getch()
    selectionValid = "False"
    displayInstanceList(OutputText, "yes")
    while selectionValid != "True":
        printWithoutCR("Enter %s#%s of instance to %s (%s1%s-%s%i%s) [%s0 aborts%s]: " % (CLRwarning, CLRnormal, actionType, CLRwarning, CLRnormal, CLRwarning, numInstances, CLRnormal, CLRtitle, CLRnormal))
        RawkeyEntered = getch()
        printWithoutCR(RawkeyEntered)
        try:
            KeyEntered = int(RawkeyEntered)
        except:
            KeyEntered = RawkeyEntered
        if KeyEntered == 0:
            print("\n\n%saborting%s - %s instance\n" % (CLRerror, CLRnormal, actionType))
            sys.exit()
        if KeyEntered >= 1 and KeyEntered <= numInstances:
            instanceForAction = KeyEntered - 1
            selectionValid = "True"
        else:
            printWithoutCR("\n%sInvalid entry:%s enter a number between 1 and %s.\n" % (CLRerror, CLRnormal, numInstances))
    print()
    return (instanceForAction)

def debugPrintList():
    print("%sDebug Listing of Info by Type%s\n" % (CLRheading2, CLRnormal))
    printList(instanceID, "instanceID")
    printList(instanceState, "instanceState")
    printList(instanceAMI, "instanceAMI")
    printList(instanceName, "instanceName")
    printList(instanceAMIName, "instanceAMIName")

################################################################################
#  Execution Begins

def main():

    global ec2C
    global ec2R
    global numInstances
    global instanceID
    global instanceState
    global instanceAMI
    global instanceName
    global instanceAMIName

    instanceID = {}
    instanceState = {}
    instanceAMI = {}
    instanceName = {}
    instanceAMIName = {}

    # Setup AWS EC2 connections
    ec2C = boto3.client('ec2')
    ec2R = boto3.resource('ec2')

    (actionType, filterType, filterType2, filters, OutputText, debug, nopem, loginuser) = getArguments()
    setupColor()

    if (debug):
        print("actionType = ", actionType)
        print("filterType = ", filterType)
        print("filterType2 = ", filterType2)
        print("filters = ", filters)
        print("OutputText = ", OutputText)
        print("nopem = ", nopem)
        print("loginuser = ", loginuser)


    if actionType != "list" and filterType == "":
        print("%sError%s - instance identifier not specified" % (CLRerror, CLRnormal))
        sys.exit()

    (instanceID, numInstances) = getInstanceIDs(filterType, filters)
    (instanceState, instanceAMI, instanceName, instanceAMIName) = getInstanceDetails(numInstances, instanceID)

    if actionType == "list":
        if numInstances > 0:
            displayInstanceList(OutputText)
        else:
            print("No instance '%s' found." % (filters))
    else:
        numInstances = refineInstanceList(numInstances, filterType2)
        if numInstances == 0:
            print("No instance '%s' found %s." % (filters, filterType2))
            sys.exit()
        if numInstances > 1:
            print("\n%s instances match these parameters:\n" % (numInstances))
            instanceForAction = selectFromList(OutputText, actionType)
        else:
            instanceForAction = 0
        instanceIDForAction = instanceID[instanceForAction]
        print("\n%s%sing%s instance: %s%s%s with id: %s%s%s" % (colorInstanceStatus(actionType), actionType, CLRnormal, CLRtitle, filters, CLRnormal, CLRtitle, instanceIDForAction, CLRnormal))
        if actionType == "start":
            print("starting")
            # ec2 command to start & results
        elif actionType == "stop":
            print("stopping")
            # ec2 command to stop & results
        elif actionType == "ssh":
            print("sshing")
            (instanceIP, instanceKey) = getInstanceConnectInfo(instanceIDForAction)
            if (debug):
                print("target IP= ", instanceIP)
                print("target key = ", instanceKey)
            # ec2 command to connect via ssh & results

    sys.exit()

if __name__ == '__main__':
    main()
